volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/lmiguel-/data/wordpress
            o: bind
            type: none
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/lmiguel-/data/mariadb
            o: bind
            type: none

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx

        build: ./mandatory/nginx/.

        image: nginx:42

        volumes:
            - wordpress:/var/www/html

        ports:
            - 443:443

        env_file:
            - .env

        depends_on:
            - wordpress

        networks:
            - inception

        restart: always

    mariadb:
        container_name: mariadb

        build: ./mandatory/mariadb/.

        image: mariadb:42

        volumes:
            - mariadb:/var/lib/mysql

        env_file:
            - .env

        networks:
            - inception
        
        restart: always

    wordpress:
        container_name: wordpress

        build: ./mandatory/wordpress/.

        image: wordpress:42

        depends_on:
            - mariadb

        volumes:
            - wordpress:/var/www/html

        env_file:
            - .env

        networks:
            - inception

        restart: always