FROM debian:oldstable

RUN apt-get update -y 

RUN apt-get install mariadb-server -y

COPY ./script/50-server.cnf /etc/mysql/mariadb.conf.d/

COPY ./script/mariadb-script.sh /

RUN chmod +x /mariadb-script.sh

CMD ["bash", "/mariadb-script.sh"]